version: "3.9"
services:
  db:
    container_name: db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=/run/secrets/postgres_auth
      - POSTGRES_USER=/run/secrets/postgres_auth
      - POSTGRES_PASSWORD=/run/secrets/postgres_auth
    secrets:
      - postgres_auth

  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

secrets:
  postgres_auth:
    file: ./database/postgres_auth.txt
  backend_auth:
    file: ./database/postgres_auth.txt

volumes:
  pgdata: {}
